services:
  db:
    image: mysql:latest
    ports:
      - ${DB_PORT}:3306
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: TRUE
    volumes:
      - mysql_volume:/var/lib/mysql
volumes:
  mysql_volume:
